package com.github.sshailabh.antlr4mcp.codegen;

import lombok.Builder;
import lombok.Data;

/**
 * Represents a file generated by ANTLR compilation
 */
@Data
@Builder
public class GeneratedFile {
    private String fileName;
    private String content;
    private TargetLanguage targetLanguage;
    private String fileType; // lexer, parser, listener, visitor, tokens, etc.

    public int getLineCount() {
        if (content == null) {
            return 0;
        }
        return (int) content.lines().count();
    }

    public long getSize() {
        if (content == null) {
            return 0;
        }
        return content.length();
    }
}
