spring:
  application:
    name: antlr4-mcp-server
  main:
    banner-mode: "off"  # Disable Spring Boot banner
    log-startup-info: false  # Disable startup logs

logging:
  file:
    name: logs/antlr4-mcp-server.log
  level:
    root: INFO
    com.github.sshailabh.antlr4mcp: INFO
    org.springframework: WARN
    org.hibernate: WARN
  pattern:
    console: ""
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{40} - %msg%n"

antlr:
  jar-path: /app/libs/antlr-4.13.2-complete.jar
  max-grammar-size-mb: 10
  max-input-size-mb: 1
  max-response-size-kb: 50
  compilation-timeout-seconds: 30
  security:
    enabled: true
    validation:
      enabled: true
    resource-limits:
      enabled: true

  # Phase 2 Configuration
  mcp:
    version: "2.0"

    cache:
      enabled: true
      max-size: 1000
      ttl-seconds: 3600

    resources:
      enabled: true
      allowed-paths:
        - ${user.home}/workspace/grammars
        - ${user.home}/projects/antlr
      auto-discovery: true

    performance:
      max-grammar-size-mb: 10
      parse-timeout-seconds: 30
      max-concurrent-requests: 50
      async-threshold-ms: 5000

    features:
      import-resolution: true
      visualization: true
      test-generation: true

    security:
      validate-inputs: true
      sanitize-paths: true
      max-import-depth: 10
